In [1]:
import pandas as pd
import numpy as np
import cyrtranslit 

data = pd.read_excel("D:\Programing projects\Master_rad\data\Podaci_za_sve_masine.xlsx")

In [2]:
data.head()

Rbr  Dan Datum Masina MOTORNI SAT                                  RAD  \
0  10562  NaN   NaN    NaN         NaN  reduktor mehanizma dizanja/lom zuba   
1  10563  NaN   NaN    NaN         NaN  reduktor mehanizma dizanja/lom zuba   
2  10564  NaN   NaN    NaN         NaN  reduktor mehanizma dizanja/lom zuba   
3  10565  NaN   NaN    NaN         NaN  reduktor mehanizma dizanja/lom zuba   
4  10566  NaN   NaN    NaN         NaN  reduktor mehanizma dizanja/lom zuba   

  VRSTA MASINE  Vreme                                Uzrok  Tehnoloski  \
0         KRAN    600  reduktor mehanizma dizanja/lom zuba         NaN   
1         KRAN    600  reduktor mehanizma dizanja/lom zuba         NaN   
2         KRAN    600  reduktor mehanizma dizanja/lom zuba         NaN   
3         KRAN    600  reduktor mehanizma dizanja/lom zuba         NaN   
4         KRAN    600  reduktor mehanizma dizanja/lom zuba         NaN   

   Elektro/struja  Mehanicki  Zloupotreba  Organizacioni  Eksterni uticaj  \
0             NaN      600.0        600.0            NaN              NaN   
1             NaN      600.0        600.0            NaN              NaN   
2             NaN      600.0        600.0            NaN              NaN   
3             NaN      600.0        600.0            NaN              NaN   
4             NaN      600.0        600.0            NaN              NaN   

   Nor stepen opasnosti  
0                     5  
1                     5  
2                     5  
3                     5  
4                     5

In [3]:
df = data[['RAD', 'Uzrok']]

In [4]:
for column in df.columns:
    print(f' {column} has missing {sum(df[column].isna())}')

 RAD has missing 0
 Uzrok has missing 4197


In [5]:
def from_cyr_to_latin(data_frame: pd.DataFrame, column):
    return data_frame[column].apply(lambda x: cyrtranslit.to_latin(x) if (type(x)==str) else x)

In [6]:
df['RAD'] = from_cyr_to_latin(df, 'RAD')
df['Uzrok'] = from_cyr_to_latin(df, 'Uzrok')

C:\Users\Luka\AppData\Local\Temp/ipykernel_864/2127116340.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['RAD'] = from_cyr_to_latin(df, 'RAD')
C:\Users\Luka\AppData\Local\Temp/ipykernel_864/2127116340.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Uzrok'] = from_cyr_to_latin(df, 'Uzrok')


In [7]:
for column in df.columns:
    df[column] = df[column].str.lower()
    df[column] = df[column].apply(lambda x: x.strip() if (type(x)==str) else x)

C:\Users\Luka\AppData\Local\Temp/ipykernel_864/4138496221.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column] = df[column].str.lower()
C:\Users\Luka\AppData\Local\Temp/ipykernel_864/4138496221.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column] = df[column].apply(lambda x: x.strip() if (type(x)==str) else x)


In [8]:
df.Uzrok.unique().shape

(157,)

In [9]:
df.RAD.unique().shape

(1571,)

In [10]:
df.Uzrok.fillna('RAD', inplace = True)

c:\Users\Luka\Anaconda3\lib\site-packages\pandas\core\generic.py:6392: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)


In [11]:
for column in df.columns:
    print(f' {column} has missing {sum(df[column].isna())}')

 RAD has missing 0
 Uzrok has missing 0


In [12]:
sentences = df.RAD.unique()
sentences
df.Uzrok.unique().shape

(157,)

In [13]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('paraphrase-multilingual-mpnet-base-v2')

sentences_embeddings = model.encode(sentences)

In [14]:
ner_encoding_list = list()
for column in df.columns:
        ner_encoding_list.append(model.encode(df[column].unique()))

ner_encoding_list

[array([[ 0.02429377, -0.1618515 , -0.01689526, ...,  0.02581038,
         -0.0816184 , -0.0741905 ],
        [-0.09757046, -0.11989342, -0.01838072, ...,  0.00884921,
         -0.11275939, -0.0218655 ],
        [ 0.02557757, -0.06794681, -0.0195236 , ...,  0.0797305 ,
         -0.04274921, -0.07629243],
        ...,
        [ 0.04613087,  0.05550788, -0.01395162, ...,  0.07128673,
         -0.04377558, -0.12902145],
        [-0.11013741, -0.12888435, -0.02084145, ...,  0.02316191,
         -0.13572414, -0.05098673],
        [-0.0941066 , -0.08938599, -0.01604381, ..., -0.01187518,
         -0.13764396, -0.0150283 ]], dtype=float32),
 array([[ 0.02429377, -0.1618515 , -0.01689526, ...,  0.02581038,
         -0.0816184 , -0.0741905 ],
        [-0.09757046, -0.11989342, -0.01838072, ...,  0.00884921,
         -0.11275939, -0.0218655 ],
        [ 0.02557757, -0.06794681, -0.0195236 , ...,  0.0797305 ,
         -0.04274921, -0.07629243],
        ...,
        [ 0.0461309 ,  0.05550787, -0.0

In [15]:
len(ner_encoding_list[1])

157

In [16]:
user_input = 'dugmici najbitnije elektro kutije krana'
evaluating_sentence = model.encode(user_input)

In [17]:
from sentence_transformers.util import cos_sim

similarity = cos_sim(evaluating_sentence, sentences_embeddings)
similarity

tensor([[0.4871, 0.6887, 0.4596,  ..., 0.4388, 0.8395, 0.5497]])

In [25]:
sentences[similarity.argmax()]

'osigurači glavnog elektroormana krana'

In [26]:
df.RAD.unique()[similarity.argmax()]

'osigurači glavnog elektroormana krana'

In [18]:
np.argmax(similarity)

tensor(1569)

In [19]:
id2sentance = {str(i): label for i, label in enumerate(df.RAD.unique())}

In [20]:
most_simular_sentence = id2sentance[str(int(np.argmax(similarity)))]
print('Recenica koju je korisnik uneo: {},\n je najbliza recenici: {}'.format(user_input, most_simular_sentence) )

Recenica koju je korisnik uneo: dugmici najbitnije elektro kutije krana,
 je najbliza recenici: osigurači glavnog elektroormana krana


In [21]:
sentences_embeddings

array([[ 0.02429377, -0.1618515 , -0.01689526, ...,  0.02581038,
        -0.0816184 , -0.0741905 ],
       [-0.09757046, -0.11989342, -0.01838072, ...,  0.00884921,
        -0.11275939, -0.0218655 ],
       [ 0.02557757, -0.06794681, -0.0195236 , ...,  0.0797305 ,
        -0.04274921, -0.07629243],
       ...,
       [ 0.04613087,  0.05550788, -0.01395162, ...,  0.07128673,
        -0.04377558, -0.12902145],
       [-0.11013741, -0.12888435, -0.02084145, ...,  0.02316191,
        -0.13572414, -0.05098673],
       [-0.0941066 , -0.08938599, -0.01604381, ..., -0.01187518,
        -0.13764396, -0.0150283 ]], dtype=float32)